### ISSUE TITLE
Info on PnP JS Console

### ISSUE THREAD

**Issue by joelfmrodrigues** [tavikukko/Chrome-SP-Editor#68]
Hi,

Just a quick suggestion to make it easier for new people to understand how to execute the code from the PnPjs console: add a comment at the top :)

![image](https://user-images.githubusercontent.com/19577724/76341360-d5fea880-62f4-11ea-99b4-19d91200ae72.png)

**Comment by koltyakov** [comment]
Isn't it already there? ;)

![image](https://user-images.githubusercontent.com/7816483/76341782-91800680-630e-11ea-834c-c356c4cc8028.png)

**Comment by joelfmrodrigues** [comment]
Didn't see it on Edge

**Comment by tavikukko** [comment]
Thanks @joelfmrodrigues for pointing that out!
Will add it in next release.

**Comment by tavikukko** [comment]
Will do something like this.
![image](https://user-images.githubusercontent.com/2223355/76417643-e589fa00-63a5-11ea-807f-2aa09d16e58f.png)
At the moment I'm working with Web Properties feature and this will be out when thats ready.
Just wondering should I default the Import to @pnp/sp/presets/all instead of "promoting" the selective imports.. any thoughts?

**Comment by tavikukko** [comment]
This fixed now in latest 6.0.2 version, just published to Edge store.
Thanks.
