### ISSUE TITLE
Unable to load _spPageContextInfo in popup.html

### ISSUE THREAD

**Issue by sankarkumar23** [tavikukko/Chrome-SP-Editor#95]
I am getting below error while loading pagecontentinfo in popup.html

![image](https://user-images.githubusercontent.com/12550023/135809117-9503dd34-1079-45c9-bc3d-2e1da498ddcb.png)

![image](https://user-images.githubusercontent.com/12550023/135809236-c9d77593-fed8-4406-a0f4-aee43650c571.png)

**Comment by tavikukko** [comment]
@sankarkumar23 which page in SharePoint you got this?

**Comment by sankarkumar23** [comment]
Any SharePoint page. It never worked for me.. the popup.html is not showing the properties.
Looks like JSON.stringfy has circular references which is causing the issue.

![image](https://user-images.githubusercontent.com/12550023/137111047-4bc137ee-4556-4665-8163-bff5a7f00d18.png)

**Comment by sankarkumar23** [comment]
I noticed it was working fine for some site collections and not for some. It appears its not working for certain site templates.

**Comment by tavikukko** [comment]
thanks @sankarkumar23 !
Could you try to check what type of SiteCollection is it? That would help me to discover the reason and provide a fix. Cheers!

**Comment by anoopt** [comment]
@tavikukko - Thank you for this extension. I use this almost everyday. 

One of the features I like the most is the extension popup which provides links to various SharePoint (system?) pages. That popup works on all pages, however I have seen it not working in the modern list page i.e. if we navigate to any modern list (`/sites/contoso/lists/listname`) and click on the extension, we do not see the links loading.

We see the below

![image](https://user-images.githubusercontent.com/9694225/209991323-e7c5721d-5100-445f-9a50-19b18d15eab3.png)

and the error message is similar to the one shared originally earlier

![image](https://user-images.githubusercontent.com/9694225/209991391-069148d4-d652-4f52-9878-890df5ceb4ef.png)

### Potential fix

It looks like the `dataSyncClient` property of the `_spPageContextInfo` is the culprit which is preventing `JSON.stringify` to run in the [`getContext` function](https://github.com/tavikukko/Chrome-SP-Editor/blob/master/app/js/getContext.js#L5).

So if we remove the `dataSyncClient` property then `JSON.stringify` runs fine. A function like below can be used

```js
var removePropertyFromObject = function (propertyName, objectToBeProcessed) { 
    let { [propertyName]: _, ...objectWithoutProperty } = objectToBeProcessed; 
    return objectWithoutProperty; 
}

removePropertyFromObject("dataSyncClient", _spPageContextInfo)
```

But when this issue was reported, the property causing the error was different (as per the first screenshot when the issue was raised). So, not sure if the fix I have suggested is the right one?

I am using Edge (chromium) version 108.0.1462.54 and 110.0.1556.0 dev .

Happy to provide more information if needed.

**Comment by tavikukko** [comment]
Hi @anoopt 
Thanks for the fix, I'll apply it and test if it work!
Thanks!

**Comment by tavikukko** [comment]
The fix worked, it will be part of the next release, which is in Review at the Chrome Store.
Thanks and happy new year!
